export type IngredientCategory =
  | 'Gemüse & Obst'
  | 'Fleisch & Fisch'
  | 'Mopro'
  | 'Trockensortiment'
  | 'Tiefkühl'
  | 'Vorrat'
  | 'Sonstiges';

export interface Nutrients {
  calories: number;
  protein: number;
  fat: number;
  carbs: number;
}

export interface BaselineIngredient {
  id: string;
  name: string;
  aliases?: string[];
  category: IngredientCategory;
  base_unit: 'g' | 'ml' | 'Stück';
  default_weight_per_piece?: number;
  default_weight_per_unit?: Record<string, number>;
  nutrients_per_100g?: Nutrients;
  nutrients_per_100ml?: Nutrients;
}

export const BASELINE_INGREDIENTS: BaselineIngredient[] = [
  // ─── Öle & Fette ─────────────────────────────────────────────────────────────
  {
    id: 'olivenoel',
    name: 'Olivenöl',
    aliases: ['öl', 'speiseöl', 'erdnussöl', 'kokosöl', 'rapsöl', 'sonnenblumenöl'],
    category: 'Vorrat',
    base_unit: 'ml',
    default_weight_per_unit: { EL: 15, TL: 5, Schuss: 10 },
    nutrients_per_100ml: { calories: 884, protein: 0, fat: 100, carbs: 0 },
  },
  {
    id: 'butter',
    name: 'Butter',
    aliases: ['süßrahmbutter', 'butterschmalz'],
    category: 'Mopro',
    base_unit: 'g',
    default_weight_per_unit: { EL: 15, TL: 5, Stück: 250 },
    nutrients_per_100g: { calories: 717, protein: 0.8, fat: 81.0, carbs: 0.1 },
  },
  {
    id: 'sesamoel',
    name: 'Sesamöl',
    aliases: ['geröstetes sesamöl', 'sesamöl'],
    category: 'Vorrat',
    base_unit: 'ml',
    default_weight_per_unit: { EL: 15, TL: 5 },
    nutrients_per_100ml: { calories: 884, protein: 0, fat: 100, carbs: 0 },
  },
  // ─── Milchprodukte ────────────────────────────────────────────────────────────
  {
    id: 'sahne',
    name: 'Sahne',
    aliases: ['schlagsahne'],
    category: 'Mopro',
    base_unit: 'ml',
    default_weight_per_unit: { EL: 15, Becher: 200 },
    nutrients_per_100ml: { calories: 292, protein: 2.4, fat: 30.0, carbs: 3.2 },
  },
  {
    id: 'milch',
    name: 'Milch',
    aliases: ['hafermilch', 'vollmilch', 'milch oder haferdrink', 'haferdrink', 'pflanzenmilch'],
    category: 'Mopro',
    base_unit: 'ml',
    default_weight_per_unit: { Becher: 200, Glas: 200 },
    nutrients_per_100ml: { calories: 64, protein: 3.4, fat: 3.7, carbs: 4.9 },
  },
  {
    id: 'parmesan',
    name: 'Parmesan',
    aliases: ['parmigiano reggiano', 'parmesankäse'],
    category: 'Mopro',
    base_unit: 'g',
    default_weight_per_unit: { EL: 10 },
    nutrients_per_100g: { calories: 431, protein: 38.0, fat: 29.0, carbs: 4.1 },
  },
  {
    id: 'ei',
    name: 'Ei',
    aliases: ['eier', 'eigelb'],
    category: 'Mopro',
    base_unit: 'Stück',
    default_weight_per_piece: 55,
    nutrients_per_100g: { calories: 155, protein: 13.0, fat: 11.0, carbs: 1.1 },
  },
  {
    id: 'joghurt',
    name: 'Griechischer Joghurt',
    aliases: ['naturjoghurt', 'joghurt'],
    category: 'Mopro',
    base_unit: 'g',
    default_weight_per_unit: { Becher: 150, 'Großer Becher': 500 },
    nutrients_per_100g: { calories: 115, protein: 9.0, fat: 10.0, carbs: 4.0 },
  },
  {
    id: 'feta',
    name: 'Fetakäse',
    aliases: ['feta', 'schafskäse', 'schafkäse'],
    category: 'Mopro',
    base_unit: 'g',
    default_weight_per_unit: { Packung: 200 },
    nutrients_per_100g: { calories: 264, protein: 14.0, fat: 21.0, carbs: 4.0 },
  },
  {
    id: 'gouda',
    name: 'Gouda',
    aliases: ['käse', 'emmentaler', 'cheddar', 'gruyère'],
    category: 'Mopro',
    base_unit: 'g',
    nutrients_per_100g: { calories: 350, protein: 25.0, fat: 27.0, carbs: 0 },
  },
  {
    id: 'creme_fraiche',
    name: 'Crème fraîche',
    aliases: ['schmand', 'crème fraiche', 'creme fraiche', 'crème fraîche'],
    category: 'Mopro',
    base_unit: 'g',
    default_weight_per_unit: { Becher: 150, EL: 15 },
    nutrients_per_100g: { calories: 292, protein: 2.4, fat: 30.0, carbs: 3.0 },
  },
  {
    id: 'ricotta',
    name: 'Ricotta',
    category: 'Mopro',
    base_unit: 'g',
    nutrients_per_100g: { calories: 174, protein: 11.0, fat: 13.0, carbs: 3.0 },
  },
  {
    id: 'mozzarella',
    name: 'Mozzarella',
    aliases: ['büffelmozzarella'],
    category: 'Mopro',
    base_unit: 'g',
    default_weight_per_unit: { Packung: 125 },
    nutrients_per_100g: { calories: 280, protein: 18.0, fat: 22.0, carbs: 2.5 },
  },
  // ─── Fleisch & Fisch ──────────────────────────────────────────────────────────
  {
    id: 'haehnchenbrust',
    name: 'Hähnchenbrust',
    aliases: ['hähnchen', 'hühnerbrust', 'hähnchenbrustfilet'],
    category: 'Fleisch & Fisch',
    base_unit: 'g',
    nutrients_per_100g: { calories: 110, protein: 23.0, fat: 1.2, carbs: 0 },
  },
  {
    id: 'lamm',
    name: 'Lammkeule',
    aliases: ['lamm', 'lammfleisch', 'lammgehacktes'],
    category: 'Fleisch & Fisch',
    base_unit: 'g',
    nutrients_per_100g: { calories: 234, protein: 18.0, fat: 18.0, carbs: 0 },
  },
  {
    id: 'rinderhack',
    name: 'Rinderhackfleisch',
    aliases: ['hackfleisch', 'rinderhack', 'gehacktes halb und halb', 'burger patties', 'patties'],
    category: 'Fleisch & Fisch',
    base_unit: 'g',
    nutrients_per_100g: { calories: 250, protein: 19.0, fat: 20.0, carbs: 0 },
  },
  {
    id: 'schinken',
    name: 'Gekochter Schinken',
    aliases: ['schinken'],
    category: 'Fleisch & Fisch',
    base_unit: 'g',
    nutrients_per_100g: { calories: 110, protein: 18.0, fat: 4.0, carbs: 1.0 },
  },
  {
    id: 'lachs',
    name: 'Lachsfilet',
    aliases: ['lachs', 'wildlachs'],
    category: 'Fleisch & Fisch',
    base_unit: 'g',
    nutrients_per_100g: { calories: 208, protein: 20.0, fat: 13.0, carbs: 0 },
  },
  {
    id: 'thunfisch_dose',
    name: 'Thunfisch (Dose)',
    aliases: ['thunfisch'],
    category: 'Fleisch & Fisch',
    base_unit: 'g',
    default_weight_per_unit: { Dose: 185, Abtropfgewicht: 140 },
    nutrients_per_100g: { calories: 113, protein: 26.0, fat: 1.0, carbs: 0 },
  },
  // ─── Gemüse ───────────────────────────────────────────────────────────────────
  {
    id: 'zwiebel',
    name: 'Zwiebel',
    aliases: ['rote zwiebeln', 'schalotten', 'frühlingszwiebeln', 'zwiebelschmelz'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_piece: 80,
    nutrients_per_100g: { calories: 40, protein: 1.1, fat: 0.1, carbs: 9.0 },
  },
  {
    id: 'knoblauch',
    name: 'Knoblauch',
    aliases: ['knoblauchzehe', 'knoblauchzehen', 'knoblauchknolle'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_piece: 3,
    nutrients_per_100g: { calories: 149, protein: 6.4, fat: 0.5, carbs: 33.0 },
  },
  {
    id: 'moehre',
    name: 'Möhre',
    aliases: ['karotte', 'mohrrübe', 'dicke möhren'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_piece: 80,
    nutrients_per_100g: { calories: 41, protein: 0.9, fat: 0.2, carbs: 10.0 },
  },
  {
    id: 'kartoffel',
    name: 'Kartoffeln',
    aliases: ['süßkartoffeln', 'süßkartoffel'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_piece: 70,
    nutrients_per_100g: { calories: 77, protein: 2.0, fat: 0.1, carbs: 17.0 },
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    aliases: ['zucchino'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_piece: 200,
    nutrients_per_100g: { calories: 17, protein: 1.2, fat: 0.3, carbs: 3.1 },
  },
  {
    id: 'paprika',
    name: 'Paprika',
    aliases: ['gelbe paprikaschote', 'rote paprikaschote', 'spitzpaprika', 'paprikaschoten'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_piece: 150,
    nutrients_per_100g: { calories: 31, protein: 1.0, fat: 0.3, carbs: 6.0 },
  },
  {
    id: 'champignons',
    name: 'Champignons',
    aliases: ['pilze', 'champignon', 'braune champignons', 'steinpilze', 'shiitake'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_piece: 20,
    nutrients_per_100g: { calories: 22, protein: 3.1, fat: 0.3, carbs: 3.3 },
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    aliases: ['brokkoli'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_piece: 400,
    nutrients_per_100g: { calories: 34, protein: 2.8, fat: 0.4, carbs: 7.0 },
  },
  {
    id: 'chinakohl',
    name: 'Chinakohl',
    aliases: ['pak choi', 'paksoi'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 16, protein: 1.5, fat: 0.2, carbs: 2.2 },
  },
  {
    id: 'spitzkohl',
    name: 'Spitzkohl',
    aliases: ['weißkohl', 'rotkohl', 'kohl', 'wirsingkohl'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 25, protein: 1.3, fat: 0.1, carbs: 5.8 },
  },
  {
    id: 'porree',
    name: 'Porree',
    aliases: ['lauch', 'porrée'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 61, protein: 1.5, fat: 0.3, carbs: 14.0 },
  },
  {
    id: 'gruenkohl',
    name: 'Grünkohl',
    aliases: ['federkohl'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 49, protein: 4.3, fat: 0.9, carbs: 9.0 },
  },
  {
    id: 'rosenkohl',
    name: 'Rosenkohl',
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 43, protein: 3.4, fat: 0.5, carbs: 9.0 },
  },
  {
    id: 'blumenkohl',
    name: 'Blumenkohl',
    aliases: ['karfiol'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 25, protein: 1.9, fat: 0.1, carbs: 5.0 },
  },
  {
    id: 'spinat',
    name: 'Spinat',
    aliases: ['blattspinat', 'tiefkühlspinat', 'rahmspinat'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 23, protein: 2.9, fat: 0.4, carbs: 3.6 },
  },
  {
    id: 'tomaten_frisch',
    name: 'Tomaten',
    aliases: ['strauchtomaten', 'cocktailtomaten', 'cherrytomaten', 'flaschentomaten'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_piece: 120,
    nutrients_per_100g: { calories: 18, protein: 0.9, fat: 0.2, carbs: 3.9 },
  },
  {
    id: 'rote_bete',
    name: 'Rote Bete',
    aliases: ['randen', 'rote rübe'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 43, protein: 1.6, fat: 0.1, carbs: 10.0 },
  },
  {
    id: 'kuerbis',
    name: 'Kürbis',
    aliases: ['kürbisfleisch', 'butternutkürbis', 'hokkaido'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 26, protein: 1.0, fat: 0.1, carbs: 6.5 },
  },
  {
    id: 'mais',
    name: 'Mais',
    aliases: ['tiefkühlmais', 'zuckermais', 'maiskolben', 'körner mais'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_unit: { Paket: 300 },
    nutrients_per_100g: { calories: 86, protein: 3.2, fat: 1.2, carbs: 19.0 },
  },
  {
    id: 'erbsen',
    name: 'Erbsen',
    aliases: ['tiefkühl-erbsen', 'tiefkühlerbsen', 'grüne erbsen'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 77, protein: 5.2, fat: 0.4, carbs: 14.0 },
  },
  {
    id: 'kaiserschoten',
    name: 'Kaiserschoten',
    aliases: ['zuckerschoten', 'schnittbohnen'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 42, protein: 2.8, fat: 0.2, carbs: 7.5 },
  },
  {
    id: 'avocado',
    name: 'Avocado',
    aliases: ['reife avocado'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_piece: 200,
    nutrients_per_100g: { calories: 160, protein: 2.0, fat: 15.0, carbs: 9.0 },
  },
  {
    id: 'blattsalat',
    name: 'Blattsalat',
    aliases: ['feldsalat', 'rucola', 'salat', 'kopfsalat'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 15, protein: 1.4, fat: 0.2, carbs: 2.4 },
  },
  // ─── Obst ─────────────────────────────────────────────────────────────────────
  {
    id: 'banane',
    name: 'Banane',
    aliases: ['reife banane'],
    category: 'Gemüse & Obst',
    base_unit: 'Stück',
    default_weight_per_piece: 120,
    nutrients_per_100g: { calories: 89, protein: 1.1, fat: 0.3, carbs: 22.8 },
  },
  {
    id: 'zitrone',
    name: 'Zitrone',
    aliases: ['zitronensaft', 'bio-zitrone', 'abgeriebene zitronenschale'],
    category: 'Gemüse & Obst',
    base_unit: 'Stück',
    default_weight_per_piece: 120,
    nutrients_per_100g: { calories: 29, protein: 1.1, fat: 0.3, carbs: 9.0 },
  },
  {
    id: 'limette',
    name: 'Limette',
    aliases: ['limettensaft', 'kaffirlimettenblätter', 'kaffir-limettenblätter'],
    category: 'Gemüse & Obst',
    base_unit: 'Stück',
    default_weight_per_piece: 80,
    nutrients_per_100g: { calories: 30, protein: 0.7, fat: 0.2, carbs: 11.0 },
  },
  {
    id: 'ananas',
    name: 'Ananas',
    aliases: ['ananasstücke', 'ananas (dose)'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_piece: 800,
    nutrients_per_100g: { calories: 50, protein: 0.5, fat: 0.1, carbs: 13.0 },
  },
  // ─── Kräuter & Würzkräuter ────────────────────────────────────────────────────
  {
    id: 'koriander',
    name: 'Koriander',
    aliases: ['frischer koriander', 'korianderpulver'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 23, protein: 2.1, fat: 0.5, carbs: 3.7 },
  },
  {
    id: 'petersilie',
    name: 'Petersilie',
    aliases: ['glatte petersilie', 'krause petersilie', 'blattpetersilie'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 36, protein: 3.0, fat: 0.8, carbs: 6.3 },
  },
  {
    id: 'basilikum',
    name: 'Basilikum',
    aliases: ['thai-basilikum'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 23, protein: 3.2, fat: 0.6, carbs: 2.7 },
  },
  {
    id: 'thymian',
    name: 'Thymian',
    aliases: ['getrockneter thymian', 'thymianblättchen', 'zitronen-thymian'],
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 101, protein: 5.6, fat: 1.7, carbs: 24.0 },
  },
  {
    id: 'rosmarin',
    name: 'Rosmarin',
    aliases: ['rosmarinnadeln', 'rosmarinpulver', 'getrockneter rosmarin'],
    category: 'Vorrat',
    base_unit: 'g',
  },
  {
    id: 'oregano',
    name: 'Oregano',
    aliases: [
      'kräuter der provence', 'kräuter de provence',
      'getrockneter oregano', 'italienische kräuter',
      'getrocknete kräuter', 'kräutermischung',
    ],
    category: 'Vorrat',
    base_unit: 'g',
  },
  {
    id: 'dill',
    name: 'Dill',
    aliases: ['frischer dill', 'getrockneter dill'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
  },
  {
    id: 'minze',
    name: 'Minze',
    aliases: ['pfefferminze'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
  },
  {
    id: 'schnittlauch',
    name: 'Schnittlauch',
    category: 'Gemüse & Obst',
    base_unit: 'g',
  },
  {
    id: 'kresse',
    name: 'Kresse',
    aliases: ['gartenkresse'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
  },
  // ─── Gewürze ──────────────────────────────────────────────────────────────────
  {
    id: 'salz',
    name: 'Salz',
    aliases: ['meersalz', 'jodsalz', 'steinsalz', 'himalayasalz', 'fleur de sel'],
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 0, protein: 0, fat: 0, carbs: 0 },
  },
  {
    id: 'pfeffer',
    name: 'Pfeffer',
    aliases: ['schwarzer pfeffer', 'weißer pfeffer', 'cayennepfeffer', 'pfefferkörner'],
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 251, protein: 10.4, fat: 3.3, carbs: 64.0 },
  },
  {
    id: 'kreuzkuemmel',
    name: 'Kreuzkümmel',
    aliases: ['cumin', 'schwarzkümmel'],
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 375, protein: 18.0, fat: 22.0, carbs: 44.0 },
  },
  {
    id: 'kurkuma',
    name: 'Kurkuma',
    aliases: ['curcuma', 'gelbwurzel', 'kurkumapulver'],
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 354, protein: 8.0, fat: 10.0, carbs: 65.0 },
  },
  {
    id: 'zimt',
    name: 'Zimt',
    aliases: ['zimtpulver', 'zimtstange'],
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 247, protein: 4.0, fat: 1.2, carbs: 81.0 },
  },
  {
    id: 'paprikapulver',
    name: 'Paprikapulver',
    aliases: ['edelsüß paprika', 'geräuchertes paprikapulver'],
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 282, protein: 14.0, fat: 13.0, carbs: 54.0 },
  },
  {
    id: 'garam_masala',
    name: 'Garam Masala',
    category: 'Vorrat',
    base_unit: 'g',
  },
  {
    id: 'chaat_masala',
    name: 'Chaat Masala',
    aliases: ['chaat masala'],
    category: 'Vorrat',
    base_unit: 'g',
  },
  {
    id: 'safran',
    name: 'Safran',
    aliases: ['safranfäden', 'safranpulver', 'teel. safranfäden'],
    category: 'Vorrat',
    base_unit: 'g',
  },
  {
    id: 'kardamom',
    name: 'Kardamom',
    aliases: ['kardamomkapseln', 'kardamomkörner'],
    category: 'Vorrat',
    base_unit: 'g',
  },
  {
    id: 'lorbeer',
    name: 'Lorbeerblatt',
    aliases: ['lorbeerblätter', 'lorbeer', 'lorbeeren'],
    category: 'Vorrat',
    base_unit: 'Stück',
  },
  {
    id: 'chili',
    name: 'Chilischote',
    aliases: ['chiliflocken', 'chilipulver', 'chili', 'peperoni'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    default_weight_per_piece: 15,
    nutrients_per_100g: { calories: 40, protein: 1.9, fat: 0.4, carbs: 9.5 },
  },
  {
    id: 'ingwer',
    name: 'Ingwer',
    aliases: ['frischer ingwer', 'ingwerwurzel', 'ingwerpulver'],
    category: 'Gemüse & Obst',
    base_unit: 'g',
    nutrients_per_100g: { calories: 80, protein: 1.8, fat: 0.8, carbs: 18.0 },
  },
  // ─── Getreide, Hülsenfrüchte, Pasta ──────────────────────────────────────────
  {
    id: 'basmati_reis',
    name: 'Basmatireis',
    aliases: ['reis', 'basmatireis (ungeschält)', 'carnaroli-reis', 'parboiled-reis', 'risotto-reis'],
    category: 'Trockensortiment',
    base_unit: 'g',
    default_weight_per_unit: { Tasse: 150 },
    nutrients_per_100g: { calories: 350, protein: 7.0, fat: 0.5, carbs: 78.0 },
  },
  {
    id: 'pasta_trocken',
    name: 'Spaghetti',
    aliases: [
      'nudeln', 'pasta', 'tagliatelle', 'dinkel-spaghetti', 'dinkel-lasagne-platten',
      'lasagne-platten', 'rigatoni', 'penne', 'mezzi rigatoni', 'fusilli',
    ],
    category: 'Trockensortiment',
    base_unit: 'g',
    nutrients_per_100g: { calories: 350, protein: 12.0, fat: 1.5, carbs: 70.0 },
  },
  {
    id: 'bulgur',
    name: 'Bulgur',
    category: 'Trockensortiment',
    base_unit: 'g',
    nutrients_per_100g: { calories: 342, protein: 12.0, fat: 1.3, carbs: 63.0 },
  },
  {
    id: 'kichererbsen',
    name: 'Kichererbsen',
    aliases: ['kichererbsen (dose)'],
    category: 'Trockensortiment',
    base_unit: 'g',
    default_weight_per_unit: { Dose: 400, Abtropfgewicht: 265 },
    nutrients_per_100g: { calories: 120, protein: 7.0, fat: 2.0, carbs: 15.0 },
  },
  {
    id: 'rote_linsen',
    name: 'Rote Linsen',
    aliases: ['linsen', 'belugalinsen', 'schwarze linsen', 'grüne linsen'],
    category: 'Trockensortiment',
    base_unit: 'g',
    nutrients_per_100g: { calories: 350, protein: 24.0, fat: 1.5, carbs: 50.0 },
  },
  {
    id: 'schwarze_bohnen',
    name: 'Schwarze Bohnen',
    aliases: ['kidneybohnen', 'weiße bohnen', 'bohnen', 'dosenböhnen'],
    category: 'Trockensortiment',
    base_unit: 'g',
    default_weight_per_unit: { Dose: 400, Abtropfgewicht: 265 },
    nutrients_per_100g: { calories: 91, protein: 6.0, fat: 0.5, carbs: 14.0 },
  },
  {
    id: 'mehl',
    name: 'Mehl',
    aliases: ['weizenmehl', 'dinkelmehl', 'vollkornmehl'],
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 342, protein: 10.0, fat: 1.0, carbs: 72.0 },
  },
  {
    id: 'polenta',
    name: 'Polenta',
    aliases: ['instant-polenta', 'maisgrieß'],
    category: 'Trockensortiment',
    base_unit: 'g',
    nutrients_per_100g: { calories: 362, protein: 8.5, fat: 3.5, carbs: 74.0 },
  },
  {
    id: 'gnocchi',
    name: 'Gnocchi',
    aliases: ['gnocchis'],
    category: 'Trockensortiment',
    base_unit: 'g',
    default_weight_per_unit: { Packung: 500 },
    nutrients_per_100g: { calories: 160, protein: 3.5, fat: 0.5, carbs: 34.0 },
  },
  // ─── Konserven & Trockenware ──────────────────────────────────────────────────
  {
    id: 'tomaten_dose',
    name: 'Tomatenstücke (Dose)',
    aliases: ['passata', 'tomatenstücke', 'gehackte tomaten'],
    category: 'Trockensortiment',
    base_unit: 'g',
    default_weight_per_unit: { Dose: 400, Packung: 500 },
    nutrients_per_100g: { calories: 20, protein: 1.1, fat: 0.2, carbs: 3.5 },
  },
  {
    id: 'tomatenmark',
    name: 'Tomatenmark',
    aliases: ['tube tomatenmark', 'tomatenkonzentrat', 'tomatensugo'],
    category: 'Vorrat',
    base_unit: 'g',
    default_weight_per_unit: { EL: 20, TL: 7 },
    nutrients_per_100g: { calories: 78, protein: 4.0, fat: 0.5, carbs: 15.0 },
  },
  {
    id: 'kokosmilch',
    name: 'Kokosmilch',
    aliases: ['kokosmilch (dose)'],
    category: 'Trockensortiment',
    base_unit: 'ml',
    default_weight_per_unit: { Dose: 400 },
    nutrients_per_100ml: { calories: 230, protein: 2.3, fat: 24.0, carbs: 6.0 },
  },
  {
    id: 'kokosraspel',
    name: 'Kokosraspel',
    aliases: ['kokosflöckchen', 'geraspelte kokosnuss'],
    category: 'Trockensortiment',
    base_unit: 'g',
    default_weight_per_unit: { EL: 10 },
    nutrients_per_100g: { calories: 604, protein: 6.1, fat: 62.0, carbs: 26.0 },
  },
  // ─── Nüsse & Samen ────────────────────────────────────────────────────────────
  {
    id: 'mandeln',
    name: 'Gemahlene Mandeln',
    aliases: ['mandelmehl', 'mandelblättchen'],
    category: 'Trockensortiment',
    base_unit: 'g',
    nutrients_per_100g: { calories: 600, protein: 21.0, fat: 54.0, carbs: 10.0 },
  },
  {
    id: 'pinienkerne',
    name: 'Pinienkerne',
    category: 'Trockensortiment',
    base_unit: 'g',
    nutrients_per_100g: { calories: 673, protein: 14.0, fat: 68.0, carbs: 13.0 },
  },
  {
    id: 'sesam',
    name: 'Sesam',
    aliases: ['sesamkörner', 'schwarzer sesam', 'ungeschälter sesam'],
    category: 'Trockensortiment',
    base_unit: 'g',
    nutrients_per_100g: { calories: 573, protein: 17.0, fat: 50.0, carbs: 23.0 },
  },
  {
    id: 'tahin',
    name: 'Tahin',
    aliases: ['sesammus', 'nussmus', 'tahini'],
    category: 'Trockensortiment',
    base_unit: 'g',
    default_weight_per_unit: { EL: 15 },
    nutrients_per_100g: { calories: 595, protein: 17.0, fat: 53.0, carbs: 21.0 },
  },
  {
    id: 'kuerbiskerne',
    name: 'Kürbiskerne',
    aliases: ['sonnenblumenkerne'],
    category: 'Trockensortiment',
    base_unit: 'g',
    nutrients_per_100g: { calories: 559, protein: 30.0, fat: 46.0, carbs: 13.0 },
  },
  // ─── Süßungsmittel ────────────────────────────────────────────────────────────
  {
    id: 'zucker',
    name: 'Zucker',
    aliases: ['puderzucker', 'rohrzucker', 'kristallzucker'],
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 387, protein: 0, fat: 0, carbs: 100.0 },
  },
  {
    id: 'ahornsirup',
    name: 'Ahornsirup',
    aliases: ['honig'],
    category: 'Trockensortiment',
    base_unit: 'ml',
    default_weight_per_unit: { EL: 15, TL: 5 },
    nutrients_per_100ml: { calories: 260, protein: 0, fat: 0.1, carbs: 67.0 },
  },
  // ─── Würzsaucen & Pasten ──────────────────────────────────────────────────────
  {
    id: 'sojasauce',
    name: 'Sojasauce',
    aliases: ['sojasoße', 'tamari', 'soja-sauce'],
    category: 'Vorrat',
    base_unit: 'ml',
    default_weight_per_unit: { EL: 15, TL: 5 },
    nutrients_per_100ml: { calories: 53, protein: 7.7, fat: 0.1, carbs: 4.9 },
  },
  {
    id: 'fischsauce',
    name: 'Fischsauce',
    aliases: ['nam pla'],
    category: 'Vorrat',
    base_unit: 'ml',
    default_weight_per_unit: { EL: 15 },
  },
  {
    id: 'senf',
    name: 'Senf',
    aliases: ['dijonsenf', 'mittelscharfer senf', 'grobkörniger senf'],
    category: 'Vorrat',
    base_unit: 'g',
    default_weight_per_unit: { TL: 5, EL: 15 },
    nutrients_per_100g: { calories: 66, protein: 4.1, fat: 3.7, carbs: 6.0 },
  },
  {
    id: 'currypaste',
    name: 'Currypaste',
    aliases: ['grüne currypaste', 'gelbe currypaste'],
    category: 'Vorrat',
    base_unit: 'g',
    default_weight_per_unit: { EL: 20 },
  },
  {
    id: 'currypulver',
    name: 'Currypulver',
    aliases: ['curry', 'gewürzmischung'],
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 325, protein: 14.0, fat: 14.0, carbs: 55.0 },
  },
  {
    id: 'tamarinde',
    name: 'Tamarindenpaste',
    aliases: ['tamarinde', 'tamarind'],
    category: 'Vorrat',
    base_unit: 'g',
  },
  {
    id: 'mayonnaise',
    name: 'Mayonnaise',
    aliases: ['mayo', 'salatmayonnaise'],
    category: 'Vorrat',
    base_unit: 'g',
    default_weight_per_unit: { EL: 15 },
    nutrients_per_100g: { calories: 680, protein: 1.5, fat: 75.0, carbs: 2.5 },
  },
  {
    id: 'curry_ketchup',
    name: 'Curry-Ketchup',
    aliases: ['ketchup', 'tomatenketchup'],
    category: 'Vorrat',
    base_unit: 'g',
  },
  {
    id: 'balsamico',
    name: 'Balsamico-Essig',
    aliases: ['essig', 'rotweinessig', 'weißweinessig', 'balsamico', 'aceto balsamico'],
    category: 'Vorrat',
    base_unit: 'ml',
    default_weight_per_unit: { EL: 15 },
  },
  {
    id: 'sossenbinder',
    name: 'Soßenbinder',
    aliases: ['pfeilwurzelstärke', 'stärke', 'speisestärke', 'maisstärke'],
    category: 'Vorrat',
    base_unit: 'g',
  },
  // ─── Weine & Brühen ───────────────────────────────────────────────────────────
  {
    id: 'wein_weiss',
    name: 'Weißwein',
    aliases: ['trockener weißwein', 'weißwein trocken'],
    category: 'Vorrat',
    base_unit: 'ml',
    default_weight_per_unit: { Schuss: 50, Glas: 200 },
  },
  {
    id: 'wein_rot',
    name: 'Rotwein',
    aliases: ['trockener rotwein', 'rotwein trocken'],
    category: 'Vorrat',
    base_unit: 'ml',
    default_weight_per_unit: { Schuss: 50, Glas: 200 },
  },
  {
    id: 'gemuese_bruehe',
    name: 'Gemüsebrühe',
    aliases: ['hühnerbrühe', 'brühe', 'fleischbrühe', 'klare brühe', 'instant-brühe'],
    category: 'Vorrat',
    base_unit: 'ml',
    default_weight_per_unit: { TL: 5, EL: 15 },
    nutrients_per_100ml: { calories: 5, protein: 0.5, fat: 0.1, carbs: 0.8 },
  },
  {
    id: 'wasser',
    name: 'Wasser',
    aliases: ['mineralwasser', 'leitungswasser'],
    category: 'Vorrat',
    base_unit: 'ml',
    nutrients_per_100ml: { calories: 0, protein: 0, fat: 0, carbs: 0 },
  },
  // ─── Getreideprodukte & Backen ────────────────────────────────────────────────
  {
    id: 'fladenbrot',
    name: 'Fladenbrot',
    aliases: ['brot', 'baguette'],
    category: 'Trockensortiment',
    base_unit: 'g',
    nutrients_per_100g: { calories: 250, protein: 8.0, fat: 1.0, carbs: 50.0 },
  },
  {
    id: 'hefe',
    name: 'Hefe',
    aliases: ['trockenhefe', 'frischhefe', 'backpulver'],
    category: 'Trockensortiment',
    base_unit: 'g',
  },
  // ─── Oliven & Konserven ───────────────────────────────────────────────────────
  {
    id: 'oliven',
    name: 'Oliven',
    aliases: ['schwarze oliven', 'grüne oliven', 'kalamata oliven'],
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 145, protein: 1.0, fat: 15.0, carbs: 4.0 },
  },
  {
    id: 'meerrettich',
    name: 'Meerrettich',
    aliases: ['sahnemeerrettich', 'frischer meerrettich', 'meerrettichcreme'],
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 62, protein: 2.9, fat: 0.5, carbs: 12.0 },
  },
  {
    id: 'kapern',
    name: 'Kapern',
    category: 'Vorrat',
    base_unit: 'g',
    nutrients_per_100g: { calories: 23, protein: 2.4, fat: 0.9, carbs: 4.9 },
  },
];
